apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: logs
spec:
  version: "v1.0.0"
  image: "davidbackxdataroots/minio-func:latest"
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "set_object"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "app.py"
    srcRepo:
      url: "https://github.com/Davidbackx/minio.git"
      sourceSubPath: "/"
      revision: "main"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent 
    triggers:
      http:
        port: 8080